"""Messages the bot sends on its own: booking reminders and owner announcements (broadcasts).

Both only reach people who already wrote to the bot, both honour /stop, and neither is ever generated by an LLM:
the reminder text is fixed and the announcement is exactly what the owner typed."""
from __future__ import annotations

import logging
import threading
import time as _time
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.orm import Session

from . import bale, engine
from .auth import current_user
from .dates import jalali_str, now_tehran
from .db import SessionLocal, get_db
from .models import Bot, BotVersion, Broadcast, ChatSession, Publication, Record, User
from .spec import BotSpec
from .store import SqlStore

log = logging.getLogger("botyar.outreach")
router = APIRouter()
BROADCASTS_PER_DAY = 3
PACE_SECONDS = 0.1  # stay far below any messenger rate limit


def _live_bots(db: Session) -> dict[int, int]:
    """bot_id -> live version, for every bot published on any messenger (Bale's version wins if both)."""
    out: dict[int, int] = {}
    for ch in bale.CHANNELS.values():
        for pub in db.scalars(select(ch.pub_model)).all():
            out.setdefault(pub.bot_id, pub.version)
    return out


def _is_messenger_customer(cust: str) -> bool:
    return cust.split(":", 1)[0] in bale.CHANNELS


# ---------- reminders ----------
def reminder_text(b, r: dict, start) -> str:
    return f"⏰ یادآوری: {r.get('slot_label', b.title)} — {jalali_str(start.date())} ساعت {start:%H:%M}.\nبرای لغو یا تغییر زمان، از «ثبت‌های من» در منو استفاده کنید."


def due_reminders(db: Session, now) -> int:
    """Send every reminder whose time has come; each booking is reminded at most once. Returns how many were sent."""
    sent = 0
    for bot_id, version in _live_bots(db).items():
        ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == bot_id, BotVersion.version == version)).first()
        if ver is None:
            continue
        spec = BotSpec.model_validate(ver.spec)
        blocks = [b for b in spec.blocks if b.type == "booking" and b.reminder_hours]
        if not blocks:
            continue
        store = SqlStore(db, bot_id, sandbox=False)
        todo = []
        for b in blocks:
            for r in store.find(b.id, status="confirmed"):
                if r.get("_reminded") or not _is_messenger_customer(r.get("_cust", "")):
                    continue
                start = engine.booking_start(b, r, now.tzinfo)
                if start is None or now >= start:
                    continue
                if now >= start - timedelta(hours=b.reminder_hours):
                    booked_at = r.get("_at")
                    # booked inside the reminder window already -> the customer knows; remind nobody
                    late = booked_at and datetime.fromisoformat(booked_at) >= start - timedelta(hours=b.reminder_hours)
                    store.update(b.id, r["id"], _reminded=True)  # mark first: a crash must never cause a repeat
                    if not late:
                        todo.append({"type": "notify_customer", "cust": r["_cust"], "text": reminder_text(b, r, start)})
        db.commit()
        sent += bale.send_customer_actions(db, bot_id, todo)
    return sent


def expire_unpaid_orders(db: Session, now) -> int:
    """Orders nobody paid within the window are cancelled so their stock and discount-code use come back."""
    total = 0
    for pub in db.scalars(select(Publication)).all():
        ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == pub.bot_id, BotVersion.version == pub.version)).first()
        if ver is None:
            continue
        spec = BotSpec.model_validate(ver.spec)
        if not any(b.type == "catalog_order" and b.payment == "online" for b in spec.blocks):
            continue
        with bale._locks[pub.bot_id]:
            actions = engine.expire_unpaid(spec, SqlStore(db, pub.bot_id, sandbox=False), now)
            db.commit()
        total += len(actions)
        bale.send_customer_actions(db, pub.bot_id, actions)
    return total


def _loop():
    while True:
        _time.sleep(60)
        try:
            with SessionLocal() as db:
                due_reminders(db, now_tehran())
                expire_unpaid_orders(db, now_tehran())
        except Exception:  # noqa: BLE001
            log.exception("reminder run failed")


def start_scheduler():
    threading.Thread(target=_loop, daemon=True, name="reminders").start()


# ---------- announcements ----------
def audience(db: Session, bot_id: int) -> list[str]:
    """Customer keys ("bale:123", "tg:456") that talked to THIS bot on a messenger it is published on, are still
    linked to it (shared bots) and did not send /stop."""
    out = []
    for ch in bale.CHANNELS.values():
        pub = db.scalars(select(ch.pub_model).where(ch.pub_model.bot_id == bot_id)).first()
        if pub is None:
            continue
        prefix = f"{ch.name}:"
        rows = db.scalars(select(ChatSession).where(ChatSession.bot_id == bot_id, ChatSession.key.like(prefix + "%"))).all()
        linked = None
        if pub.mode == "shared":
            linked = {c for (c,) in db.execute(select(ch.link_model.chat_id).where(ch.link_model.pub_id == pub.id))}
        for r in rows:
            chat = r.key[len(prefix):]
            if (r.state or {}).get("muted") or (linked is not None and chat not in linked):
                continue
            out.append(r.key)
    return out


def _any_publication(db: Session, bot_id: int) -> bool:
    return any(db.scalars(select(ch.pub_model).where(ch.pub_model.bot_id == bot_id)).first() for ch in bale.CHANNELS.values())


class BroadcastIn(BaseModel):
    text: str = Field(min_length=1, max_length=1000)


def _owned_published(bot_id: int, user: User, db: Session):
    bot = db.get(Bot, bot_id)
    if not bot or bot.user_id != user.id:
        raise HTTPException(404, "ربات یافت نشد")
    if not _any_publication(db, bot_id):
        raise HTTPException(409, "ربات هنوز منتشر نشده است.")


@router.get("/api/bots/{bot_id}/broadcasts")
def list_broadcasts(bot_id: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    bot = db.get(Bot, bot_id)
    if not bot or bot.user_id != user.id:
        raise HTTPException(404, "ربات یافت نشد")
    published = _any_publication(db, bot_id)
    rows = db.scalars(select(Broadcast).where(Broadcast.bot_id == bot_id).order_by(Broadcast.id.desc()).limit(20)).all()
    return {"published": published, "audience": len(audience(db, bot_id)) if published else 0, "per_day": BROADCASTS_PER_DAY,
            "items": [{"id": b.id, "text": b.text, "audience": b.audience, "sent": b.sent, "failed": b.failed, "done": b.done,
                       "created_at": b.created_at.isoformat()} for b in rows]}


@router.post("/api/bots/{bot_id}/broadcasts")
def send_broadcast(bot_id: int, body: BroadcastIn, user: User = Depends(current_user), db: Session = Depends(get_db)):
    _owned_published(bot_id, user, db)
    text = body.text.strip()
    if not text:
        raise HTTPException(422, "متن اطلاعیه خالی است")
    day_ago = datetime.now(timezone.utc) - timedelta(hours=24)
    last = db.scalars(select(Broadcast).where(Broadcast.bot_id == bot_id).order_by(Broadcast.id.desc()).limit(BROADCASTS_PER_DAY)).all()
    recent = sum(1 for b in last if (b.created_at if b.created_at.tzinfo else b.created_at.replace(tzinfo=timezone.utc)) > day_ago)
    if recent >= BROADCASTS_PER_DAY:
        raise HTTPException(429, f"در هر شبانه‌روز حداکثر {BROADCASTS_PER_DAY} اطلاعیه می‌توانید بفرستید تا مشتری‌ها ناراحت نشوند.")
    custs = audience(db, bot_id)
    if not custs:
        raise HTTPException(409, "هنوز مشتری‌ای با ربات شما گفتگو نکرده است.")
    row = Broadcast(bot_id=bot_id, text=text, audience=len(custs))
    db.add(row)
    db.commit()
    threading.Thread(target=_deliver, args=(row.id, bot_id, custs, text), daemon=True).start()
    return {"id": row.id, "audience": len(custs)}


def _deliver(broadcast_id: int, bot_id: int, custs: list[str], text: str):
    with SessionLocal() as db:
        row = db.get(Broadcast, broadcast_id)
        tokens: dict[str, str | None] = {}  # channel name -> bot token (None: not usable)
        for ch in bale.CHANNELS.values():
            pub = db.scalars(select(ch.pub_model).where(ch.pub_model.bot_id == bot_id)).first()
            try:
                tokens[ch.name] = bale.pub_token(ch, pub) if pub else None
            except Exception:  # noqa: BLE001
                tokens[ch.name] = None
        body = engine.fa_digits(text)[:4096] + "\n\nبرای توقف اطلاعیه‌ها: /stop"
        for i, cust in enumerate(custs, 1):
            name, chat = cust.split(":", 1)
            try:
                if not tokens.get(name):
                    raise bale.BaleError(f"{name} token unavailable")
                bale.CHANNELS[name].call(tokens[name], "sendMessage", {"chat_id": chat, "text": body})
                row.sent += 1
            except Exception as e:  # noqa: BLE001
                row.failed += 1
                log.warning("broadcast send failed: %s", e)
            if i % 10 == 0:
                db.commit()
            _time.sleep(PACE_SECONDS)
        row.done = True
        db.commit()
