"""Messages the bot sends on its own: booking reminders and owner announcements (broadcasts).

Both only reach people who already wrote to the bot, both honour /stop, and neither is ever generated by an LLM:
the reminder text is fixed and the announcement is exactly what the owner typed."""
from __future__ import annotations

import logging
import threading
import time as _time
from datetime import date, datetime, time as dtime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.orm import Session

from . import anon, bale, engine, outbox, webhooks
from .auth import current_user
from .dates import TEHRAN, jalali_str, now_tehran
from .db import SessionLocal, get_db
from .models import Bot, BotVersion, Broadcast, ChatSession, OwnerDigest, Publication, Record, ScheduledBroadcast, User
from .spec import BotSpec
from .store import SqlStore

log = logging.getLogger("botyar.outreach")
router = APIRouter()
BROADCASTS_PER_DAY = 3
PACE_SECONDS = 0.1  # stay far below any messenger rate limit


def _live_bots(db: Session) -> dict[int, int]:
    """bot_id -> live version, for every bot published on any messenger (Bale's version wins if both)."""
    out: dict[int, int] = {}
    for ch in bale.CHANNELS.values():
        for pub in db.scalars(select(ch.pub_model)).all():
            out.setdefault(pub.bot_id, pub.version)
    return out


def _is_messenger_customer(cust: str) -> bool:
    return cust.split(":", 1)[0] in bale.CHANNELS


# ---------- reminders ----------
def reminder_text(b, r: dict, start, spec=None) -> str:
    mine = engine.my_label(spec) if spec is not None else engine.MY_LABEL
    tail = "\nلطفاً با دکمه‌های زیر اعلام کنید می‌آیید یا نه." if b.reminder_confirm else f"\nبرای لغو یا تغییر زمان، از «{mine}» در منو استفاده کنید."
    return f"⏰ یادآوری: {r.get('slot_label', b.title)} — {jalali_str(start.date())} ساعت {start:%H:%M}." + tail


def due_reminders(db: Session, now) -> int:
    """Send every reminder whose time has come; each booking is reminded at most once. Returns how many were sent."""
    sent = 0
    for bot_id, version in _live_bots(db).items():
        ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == bot_id, BotVersion.version == version)).first()
        if ver is None:
            continue
        spec = BotSpec.model_validate(ver.spec)
        blocks = [b for b in spec.blocks if b.type == "booking" and b.reminder_hours]
        if not blocks:
            continue
        store = SqlStore(db, bot_id, sandbox=False)
        todo = []
        for b in blocks:
            for r in store.find(b.id, status="confirmed"):
                if r.get("_reminded") or not _is_messenger_customer(r.get("_cust", "")):
                    continue
                start = engine.booking_start(b, r, now.tzinfo)
                if start is None or now >= start:
                    continue
                if now >= start - timedelta(hours=b.reminder_hours):
                    booked_at = r.get("_at")
                    # booked inside the reminder window already -> the customer knows; remind nobody
                    late = booked_at and datetime.fromisoformat(booked_at) >= start - timedelta(hours=b.reminder_hours)
                    store.update(b.id, r["id"], _reminded=True)  # mark first: a crash must never cause a repeat
                    if not late:
                        todo.append({"type": "notify_customer", "cust": r["_cust"], "text": reminder_text(b, r, start, spec),
                                     "buttons": engine.reminder_buttons(spec, b, r)})
        db.commit()
        sent += bale.send_customer_actions(db, bot_id, todo)
    return sent


def expire_unpaid_orders(db: Session, now) -> int:
    """Orders nobody paid within the window are cancelled so their stock and discount-code use come back."""
    total = 0
    for pub in db.scalars(select(Publication)).all():
        ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == pub.bot_id, BotVersion.version == pub.version)).first()
        if ver is None:
            continue
        spec = BotSpec.model_validate(ver.spec)
        if not any((b.type == "catalog_order" and b.payment in ("online", "card")) or (b.type == "booking" and b.deposit) for b in spec.blocks):
            continue
        with bale._locks[pub.bot_id]:
            actions = engine.expire_unpaid(spec, SqlStore(db, pub.bot_id, sandbox=False), now)
            db.commit()
        total += len(actions)
        bale.send_customer_actions(db, pub.bot_id, actions)
    return total


def feedback_asks(db: Session, now) -> int:
    """«از … راضی بودید؟» after appointments and delivered orders, for bots whose feedback block has `after`."""
    total = 0
    for pub in db.scalars(select(Publication)).all():
        ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == pub.bot_id, BotVersion.version == pub.version)).first()
        if ver is None or not any(b.get("type") == "feedback" and b.get("after") for b in ver.spec.get("blocks", [])):
            continue
        spec = BotSpec.model_validate(ver.spec)
        with bale._locks[pub.bot_id]:
            actions = engine.feedback_requests(spec, SqlStore(db, pub.bot_id, sandbox=False), now)
            db.commit()
        total += bale.send_customer_actions(db, pub.bot_id, actions)
    return total


def restock_alerts(db: Session, now) -> int:
    """«موجود شد خبرم کن»: tell the customers waiting for products that are back in stock."""
    total = 0
    bot_ids = set(db.scalars(select(Record.bot_id).where(Record.collection == engine.RESTOCK, Record.sandbox.is_(False))).all())
    for bot_id in bot_ids:
        pub = db.scalars(select(Publication).where(Publication.bot_id == bot_id)).first()
        ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == bot_id, BotVersion.version == pub.version)).first() if pub else None
        if ver is None:
            continue
        spec = BotSpec.model_validate(ver.spec)
        with bale._locks[bot_id]:
            actions = engine.restock_notices(spec, SqlStore(db, bot_id, sandbox=False), now)
            db.commit()
        total += bale.send_customer_actions(db, bot_id, actions)
    return total


def expire_anon_waiting(db: Session, now: datetime) -> int:
    specs: dict[int, BotSpec | None] = {}

    def limit_for(bot_id: int, block_id: str) -> int:
        if bot_id not in specs:
            from .models import TgPublication
            pub = db.scalars(select(Publication).where(Publication.bot_id == bot_id)).first() or db.scalars(select(TgPublication).where(TgPublication.bot_id == bot_id)).first()
            ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == bot_id, BotVersion.version == pub.version)).first() if pub else None
            specs[bot_id] = BotSpec.model_validate(ver.spec) if ver else None
        b = next((x for x in (specs[bot_id].blocks if specs[bot_id] else []) if x.id == block_id), None)
        return getattr(b, "max_minutes", 0) or 0

    msgs = anon.expire_waiting(db, now) + anon.expire_long_chats(db, now, limit_for)
    db.commit()
    for bot_id, action in msgs:
        bale.send_customer_actions(db, bot_id, [action])
    return len(msgs)


DIGEST_HOUR = 8  # Tehran


def digest_enabled(db: Session, bot_id: int) -> bool:
    row = db.scalars(select(OwnerDigest).where(OwnerDigest.bot_id == bot_id)).first()
    return row is None or row.enabled


def daily_digests(db: Session, now: datetime) -> int:
    """Once a day from 8:00, every live bot whose owner linked a chat (and kept the summary on) gets its brief."""
    if now.hour < DIGEST_HOUR:
        return 0
    today, sent = now.date().isoformat(), 0
    for bot_id, version in _live_bots(db).items():
        row = db.scalars(select(OwnerDigest).where(OwnerDigest.bot_id == bot_id)).first()
        if row is None:
            row = OwnerDigest(bot_id=bot_id, enabled=True, last_sent="")  # defaults apply only on insert: set them now
            db.add(row)
        if not row.enabled or row.last_sent == today:
            continue
        row.last_sent = today  # marked first: a crash must never send the summary twice
        db.commit()
        ver = db.scalars(select(BotVersion).where(BotVersion.bot_id == bot_id, BotVersion.version == version)).first()
        text = engine.daily_summary(BotSpec.model_validate(ver.spec), SqlStore(db, bot_id, sandbox=False), now.date(), now.tzinfo) if ver else None
        if text and bale.send_owner(db, bot_id, text):
            sent += 1
    return sent


class DigestIn(BaseModel):
    enabled: bool


@router.put("/api/bots/{bot_id}/digest")
def set_digest(bot_id: int, body: DigestIn, user: User = Depends(current_user), db: Session = Depends(get_db)):
    if not db.scalars(select(Bot).where(Bot.id == bot_id, Bot.user_id == user.id)).first():
        raise HTTPException(404, "ربات یافت نشد")
    row = db.scalars(select(OwnerDigest).where(OwnerDigest.bot_id == bot_id)).first() or OwnerDigest(bot_id=bot_id, last_sent="")
    row.enabled = body.enabled
    db.add(row)
    db.commit()
    return {"daily_summary": row.enabled}


def _jobs(ticks: int):
    """Each job runs on its own: one failing (or slow) job must not stop the others."""
    now_u = datetime.now(timezone.utc)
    work = [("reminders", lambda db: due_reminders(db, now_tehran())),
            ("unpaid orders", lambda db: expire_unpaid_orders(db, now_tehran())),
            ("back in stock", lambda db: restock_alerts(db, now_tehran())),
            ("feedback requests", lambda db: feedback_asks(db, now_tehran())),
            ("scheduled announcements", lambda db: due_scheduled(db, now_u)),
            ("anonymous waiting", lambda db: expire_anon_waiting(db, now_u)),
            ("daily summaries", lambda db: daily_digests(db, now_tehran())),
            ("outbox", lambda db: outbox.process(db, now_u))]
    if ticks % 15 == 0:
        work.append(("webhooks", lambda db: webhooks.refresh(db)))
    if ticks % 1440 == 0:
        work.append(("outbox purge", lambda db: outbox.purge(db, now_u)))
    for name, fn in work:
        try:
            with SessionLocal() as db:
                fn(db)
        except Exception:  # noqa: BLE001
            log.exception("background job failed: %s", name)


def _loop():
    ticks = 0
    while True:
        _time.sleep(60)
        ticks += 1
        _jobs(ticks)


def start_scheduler():
    threading.Thread(target=_loop, daemon=True, name="reminders").start()


# ---------- announcements ----------
def audience(db: Session, bot_id: int, include_muted: bool = False) -> list[str]:
    """Customer keys ("bale:123", "tg:456") that talked to THIS bot on a messenger it is published on, are still
    linked to it (shared bots) and did not send /stop (unless include_muted: news about their own booking)."""
    out = []
    for ch in bale.CHANNELS.values():
        pub = db.scalars(select(ch.pub_model).where(ch.pub_model.bot_id == bot_id)).first()
        if pub is None:
            continue
        prefix = f"{ch.name}:"
        rows = db.scalars(select(ChatSession).where(ChatSession.bot_id == bot_id, ChatSession.key.like(prefix + "%"))).all()
        linked = None
        if pub.mode == "shared":
            linked = {c for (c,) in db.execute(select(ch.link_model.chat_id).where(ch.link_model.pub_id == pub.id))}
        for r in rows:
            chat = r.key[len(prefix):]
            if ((r.state or {}).get("muted") and not include_muted) or (linked is not None and chat not in linked):
                continue
            out.append(r.key)
    return out


def _any_publication(db: Session, bot_id: int) -> bool:
    return any(db.scalars(select(ch.pub_model).where(ch.pub_model.bot_id == bot_id)).first() for ch in bale.CHANNELS.values())


class BroadcastIn(BaseModel):
    text: str = Field(min_length=1, max_length=1000)
    segment: str = "all"  # all | block:<id> | session:<block id>:<slot id>:<ISO date> | recent:<days>


def _live_spec(db: Session, bot_id: int) -> BotSpec | None:
    ver = _live_bots(db).get(bot_id)
    row = db.scalars(select(BotVersion).where(BotVersion.bot_id == bot_id, BotVersion.version == ver)).first() if ver else None
    return BotSpec.model_validate(row.spec) if row else None


def segments(db: Session, bot_id: int, today) -> list[dict]:
    """The groups an announcement can go to, each with its label and size (the size counts reachable customers)."""
    spec = _live_spec(db, bot_id)
    if spec is None:
        return []
    store = SqlStore(db, bot_id, sandbox=False)
    reach, reach_all = set(audience(db, bot_id)), set(audience(db, bot_id, include_muted=True))
    out = [{"id": "all", "label": "همه‌ی مشتریان", "size": len(reach)}]
    for days in (7, 30):
        out.append({"id": f"recent:{days}", "label": f"فعال در {days} روز گذشته", "size": len(_segment_custs(db, spec, store, f"recent:{days}", today) & reach)})
    for b in spec.blocks:
        if not getattr(b, "fields", None) and b.type not in ("quiz", "feedback"):
            continue
        n = len(_segment_custs(db, spec, store, f"block:{b.id}", today) & reach)
        if n:
            out.append({"id": f"block:{b.id}", "label": f"کسانی که در «{getattr(b, 'title', b.id)}» ثبت دارند", "size": n})
        if b.type == "booking":  # each upcoming session: its people hear about it even after /stop (it is their booking)
            sessions: dict[tuple, set] = {}
            for r in store.find(b.id):
                if r.get("status") in ("confirmed", "waitlisted") and r.get("date") and r["date"] >= today.isoformat() and r.get("_cust"):
                    sessions.setdefault((r.get("slot"), r["date"]), set()).add(r["_cust"])
            for (slot, day), custs in sorted(sessions.items(), key=lambda kv: (kv[0][1], str(kv[0][0])))[:30]:
                when = jalali_str(date.fromisoformat(day))
                name = next((f"{s.label} — {when}" for s in b.slots if s.id == slot), f"نوبت‌های {when}")
                out.append({"id": f"session:{b.id}:{slot}:{day}", "size": len(custs & reach_all), "label": f"{b.title} · {name}"})
    return out


def _segment_custs(db: Session, spec: BotSpec, store, segment: str, today) -> set[str]:
    kind, _, rest = segment.partition(":")
    if kind == "block":
        return {r["_cust"] for r in store.find(rest) if r.get("_cust") and r.get("status") != "cancelled"}
    if kind == "session":
        block_id, slot, day = rest.split(":", 2)
        return {r["_cust"] for r in store.find(block_id, slot=slot, date=day) if r.get("_cust") and r.get("status") in ("confirmed", "waitlisted")}
    if kind == "recent":
        since = (datetime.combine(today, dtime(0), tzinfo=TEHRAN) - timedelta(days=int(rest))).isoformat()
        return {r["_cust"] for b in spec.blocks for r in store.find(b.id) if r.get("_cust") and str(r.get("_at", "")) >= since}
    raise ValueError("گروه مخاطبان نامعتبر است.")


def segment_audience(db: Session, bot_id: int, segment: str, today) -> tuple[list[str], str]:
    """Who gets an announcement for this segment, and its label (empty for everyone)."""
    if segment == "all":
        return audience(db, bot_id), ""
    spec = _live_spec(db, bot_id)
    if spec is None:
        return [], ""
    opt = next((s for s in segments(db, bot_id, today) if s["id"] == segment), None)
    if opt is None:
        raise ValueError("گروه مخاطبان نامعتبر است یا دیگر وجود ندارد.")
    base = audience(db, bot_id, include_muted=segment.startswith("session:"))
    wanted = _segment_custs(db, spec, SqlStore(db, bot_id, sandbox=False), segment, today)
    return [c for c in base if c in wanted], opt["label"]


@router.get("/api/bots/{bot_id}/broadcasts/segments")
def list_segments(bot_id: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    _owned_published(bot_id, user, db)
    return segments(db, bot_id, now_tehran().date())


def _owned_published(bot_id: int, user: User, db: Session):
    bot = db.get(Bot, bot_id)
    if not bot or bot.user_id != user.id:
        raise HTTPException(404, "ربات یافت نشد")
    if not _any_publication(db, bot_id):
        raise HTTPException(409, "ربات هنوز منتشر نشده است.")


@router.get("/api/bots/{bot_id}/broadcasts")
def list_broadcasts(bot_id: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    bot = db.get(Bot, bot_id)
    if not bot or bot.user_id != user.id:
        raise HTTPException(404, "ربات یافت نشد")
    published = _any_publication(db, bot_id)
    rows = db.scalars(select(Broadcast).where(Broadcast.bot_id == bot_id).order_by(Broadcast.id.desc()).limit(20)).all()
    return {"published": published, "audience": len(audience(db, bot_id)) if published else 0, "per_day": BROADCASTS_PER_DAY,
            "items": [{"id": b.id, "text": b.text, "audience": b.audience, "sent": b.sent, "failed": b.failed, "done": b.done,
                       "segment": b.segment_label or "", "created_at": b.created_at.isoformat()} for b in rows]}


def launch_broadcast(db: Session, bot_id: int, text: str, segment: str = "all") -> Broadcast:
    """Check the daily limit and the audience, store the announcement and start delivering it in the background.
    Raises ValueError(message) when it cannot be sent (used by both the manual button and the scheduler)."""
    day_ago = datetime.now(timezone.utc) - timedelta(hours=24)
    last = db.scalars(select(Broadcast).where(Broadcast.bot_id == bot_id).order_by(Broadcast.id.desc()).limit(BROADCASTS_PER_DAY)).all()
    recent = sum(1 for b in last if (b.created_at if b.created_at.tzinfo else b.created_at.replace(tzinfo=timezone.utc)) > day_ago)
    if recent >= BROADCASTS_PER_DAY:
        raise ValueError(f"در هر شبانه‌روز حداکثر {BROADCASTS_PER_DAY} اطلاعیه (دستی و زمان‌بندی‌شده با هم) ارسال می‌شود تا مشتریان آزرده نشوند.")
    custs, label = segment_audience(db, bot_id, segment, now_tehran().date())
    if not custs:
        raise ValueError("هنوز هیچ مشتری‌ای با ربات شما گفت‌وگو نکرده است." if segment == "all" else "در این گروه مشتری‌ای برای دریافت اطلاعیه نیست.")
    row = Broadcast(bot_id=bot_id, text=text, audience=len(custs), segment_label=label)
    db.add(row)
    db.commit()
    threading.Thread(target=_deliver, args=(row.id, bot_id, custs, text), daemon=True).start()
    return row


@router.post("/api/bots/{bot_id}/broadcasts")
def send_broadcast(bot_id: int, body: BroadcastIn, user: User = Depends(current_user), db: Session = Depends(get_db)):
    _owned_published(bot_id, user, db)
    text = body.text.strip()
    if not text:
        raise HTTPException(422, "متن اطلاعیه خالی است")
    try:
        row = launch_broadcast(db, bot_id, text, body.segment)
    except ValueError as e:
        raise HTTPException(429 if "حداکثر" in str(e) else 409, str(e))
    return {"id": row.id, "audience": row.audience}


# ---------- scheduled announcements ----------
MAX_SCHEDULES = 5
MAX_AHEAD_DAYS = 90


class ScheduleIn(BaseModel):
    text: str = Field(min_length=1, max_length=1000)
    mode: str  # once | daily
    at: str = ""    # once: Tehran local "YYYY-MM-DDTHH:MM"
    time: str = ""  # daily: Tehran "HH:MM"


def _next_daily(hhmm: str, after: datetime) -> datetime:
    """The next UTC instant strictly after `after` at hh:mm Tehran time."""
    h, m = int(hhmm[:2]), int(hhmm[3:])
    local = after.astimezone(TEHRAN)
    cand = datetime.combine(local.date(), dtime(h, m), tzinfo=TEHRAN)
    if cand <= after:
        cand += timedelta(days=1)
    return cand.astimezone(timezone.utc)


def _sched_out(r: ScheduledBroadcast) -> dict:
    nxt = r.next_run if r.next_run.tzinfo else r.next_run.replace(tzinfo=timezone.utc)
    return {"id": r.id, "text": r.text, "mode": r.mode, "time": r.hhmm, "active": r.active, "next_run": nxt.astimezone(TEHRAN).isoformat(),
            "last_run": r.last_run.isoformat() if r.last_run else None, "last_status": r.last_status}


@router.get("/api/bots/{bot_id}/scheduled")
def list_scheduled(bot_id: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    bot = db.get(Bot, bot_id)
    if not bot or bot.user_id != user.id:
        raise HTTPException(404, "ربات یافت نشد")
    rows = db.scalars(select(ScheduledBroadcast).where(ScheduledBroadcast.bot_id == bot_id).order_by(ScheduledBroadcast.id.desc()).limit(30)).all()
    return {"max": MAX_SCHEDULES, "items": [_sched_out(r) for r in rows]}


@router.post("/api/bots/{bot_id}/scheduled")
def create_scheduled(bot_id: int, body: ScheduleIn, user: User = Depends(current_user), db: Session = Depends(get_db)):
    _owned_published(bot_id, user, db)
    text = body.text.strip()
    if not text:
        raise HTTPException(422, "متن اطلاعیه خالی است")
    if len(db.scalars(select(ScheduledBroadcast).where(ScheduledBroadcast.bot_id == bot_id, ScheduledBroadcast.active.is_(True))).all()) >= MAX_SCHEDULES:
        raise HTTPException(409, f"حداکثر {MAX_SCHEDULES} اطلاعیه‌ی زمان‌بندی‌شده‌ی فعال می‌توانید داشته باشید.")
    now = datetime.now(timezone.utc)
    if body.mode == "once":
        try:
            when = datetime.fromisoformat(body.at).replace(tzinfo=TEHRAN).astimezone(timezone.utc)
        except ValueError:
            raise HTTPException(422, "تاریخ و ساعت نامعتبر است")
        if when < now + timedelta(minutes=1):
            raise HTTPException(422, "زمان ارسال باید در آینده باشد")
        if when > now + timedelta(days=MAX_AHEAD_DAYS):
            raise HTTPException(422, f"زمان ارسال حداکثر {MAX_AHEAD_DAYS} روز بعد می‌تواند باشد")
        row = ScheduledBroadcast(bot_id=bot_id, text=text, mode="once", next_run=when)
    elif body.mode == "daily":
        if len(body.time) != 5 or body.time[2] != ":" or not (body.time[:2].isdigit() and body.time[3:].isdigit()) or int(body.time[:2]) > 23 or int(body.time[3:]) > 59:
            raise HTTPException(422, "ساعت باید به شکل HH:MM باشد")
        row = ScheduledBroadcast(bot_id=bot_id, text=text, mode="daily", hhmm=body.time, next_run=_next_daily(body.time, now))
    else:
        raise HTTPException(422, "نوع زمان‌بندی نامعتبر است")
    db.add(row)
    db.commit()
    return _sched_out(row)


@router.delete("/api/bots/{bot_id}/scheduled/{sid}")
def cancel_scheduled(bot_id: int, sid: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    bot = db.get(Bot, bot_id)
    if not bot or bot.user_id != user.id:
        raise HTTPException(404, "ربات یافت نشد")
    r = db.get(ScheduledBroadcast, sid)
    if r is None or r.bot_id != bot_id:
        raise HTTPException(404, "یافت نشد")
    r.active = False
    db.commit()
    return {"ok": True}


def due_scheduled(db: Session, now: datetime) -> int:
    """Run every scheduled announcement whose time has come. A one-time announcement runs once; a daily one moves to
    tomorrow. A run that cannot be delivered (daily limit, no customers, bot unpublished) is recorded and skipped, never retried in a loop."""
    n = 0
    for r in db.scalars(select(ScheduledBroadcast).where(ScheduledBroadcast.active.is_(True))).all():
        due = r.next_run if r.next_run.tzinfo else r.next_run.replace(tzinfo=timezone.utc)
        if due > now:
            continue
        r.last_run = now
        if r.mode == "daily":
            r.next_run = _next_daily(r.hhmm, now)  # advance first: a crash must not resend every minute
        else:
            r.active = False
        db.commit()
        try:
            if not _any_publication(db, r.bot_id):
                raise ValueError("ربات منتشر نشده است")
            launch_broadcast(db, r.bot_id, r.text)
            r.last_status = "ارسال شد"
            n += 1
        except ValueError as e:
            r.last_status = str(e)[:190]
        db.commit()
    return n


def _deliver(broadcast_id: int, bot_id: int, custs: list[str], text: str):
    with SessionLocal() as db:
        row = db.get(Broadcast, broadcast_id)
        tokens: dict[str, str | None] = {}  # channel name -> bot token (None: not usable)
        for ch in bale.CHANNELS.values():
            pub = db.scalars(select(ch.pub_model).where(ch.pub_model.bot_id == bot_id)).first()
            try:
                tokens[ch.name] = bale.pub_token(ch, pub) if pub else None
            except Exception:  # noqa: BLE001
                tokens[ch.name] = None
        body = engine.fa_digits(text)[:4096] + "\n\nبرای توقف اطلاعیه‌ها: /stop"
        for i, cust in enumerate(custs, 1):
            name, chat = cust.split(":", 1)
            try:
                if not tokens.get(name):
                    raise bale.BaleError(f"{name} token unavailable")
                outbox.send(bale.CHANNELS[name], tokens[name], "sendMessage", {"chat_id": chat, "text": body}, bot_id, db)  # queued if unreachable
                row.sent += 1
            except Exception as e:  # noqa: BLE001
                row.failed += 1
                log.warning("broadcast send failed: %s", e)
            if i % 10 == 0:
                db.commit()
            _time.sleep(PACE_SECONDS)
        row.done = True
        db.commit()
